const firebaseConfig={apiKey:"AIzaSyCjTn-hyUdZGiDHsy5_ijYu6KQCYMElsTI",authDomain:"casinorewards-95502.firebaseapp.com",databaseURL:"https://casinorewards-95502-default-rtdb.firebaseio.com",projectId:"casinorewards-95502",storageBucket:"casinorewards-95502.firebasestorage.app",messagingSenderId:"768311187647",appId:"1:768311187647:web:e26e8a5134a003ef634e0a"};
if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);
const db=firebase.database(),SESSION_KEY="cia_auth",REMEMBER_KEY="cia_remembered";
let globalFirewallActive=false;
function toggleDropdown(id){document.getElementById(id).classList.toggle('open');}
function showMasterKeyPopup(){document.getElementById('keyPopup').style.display='flex';}
function closeKeyPopup(){document.getElementById('keyPopup').style.display='none';}
async function getMasterKey(){const s=await db.ref('admin/masterKey').once('value');if(s.exists())return s.val();await db.ref('admin/masterKey').set("CIA2024");return "CIA2024";}
async function updateMasterKey(){const k=document.getElementById('popupNewKey').value.trim();if(!k||k.length<4)return alert("Key must be at least 4 chars");if(confirm(`Change master key to "${k}"?`)){await db.ref('admin/masterKey').set(k);alert("Master key updated!");closeKeyPopup();localStorage.removeItem(REMEMBER_KEY);logout();}}
function generateHash(u){if(!u)return '#00000000';let h=0;for(let i=0;i<u.length;i++){h=((h<<5)-h)+u.charCodeAt(i);h|=0;}return '#'+Math.abs(h).toString(16).substring(0,8);}
async function verifyAccess(){const i=document.getElementById('accessKey').value,m=await getMasterKey();if(i===m){sessionStorage.setItem(SESSION_KEY,"true");localStorage.setItem(REMEMBER_KEY,"true");document.getElementById('loginOverlay').style.display='none';document.getElementById('dashboard').classList.add('active');loadStats();checkGlobalFirewallStatus();}else{document.getElementById('loginError').innerHTML="ACCESS DENIED!";}}
function logout(){sessionStorage.removeItem(SESSION_KEY);localStorage.removeItem(REMEMBER_KEY);document.getElementById('loginOverlay').style.display='flex';document.getElementById('dashboard').classList.remove('active');}
function deploy(){const v=document.getElementById('links').value.trim();if(!v)return;v.split('\n').forEach(u=>{if(u.trim())db.ref('links').push({url:u.trim(),hash:generateHash(u.trim()),status:'available',user:'NONE',createdAt:Date.now()});});document.getElementById('links').value='';}
function reuseLink(k){if(confirm("Recycle this link?"))db.ref('links/'+k).update({status:'available',user:'NONE'});}
async function toggleFirewall(){const b=document.getElementById('firewallToggleBtn'),s=document.getElementById('firewallStatusMsg');if(!globalFirewallActive){if(confirm("ACTIVATE GLOBAL FIREWALL?")){await db.ref('admin/globalFirewall').set({active:true,activatedBy:"ADMIN",timestamp:Date.now()});globalFirewallActive=true;b.className='firewall-on';b.innerHTML='🔥 FIREWALL ON 🔥';s.innerHTML='FIREWALL ACTIVE';s.style.color='#ff4444';b.classList.add('fire-animation');alert("🔥 FIREWALL ACTIVATED");}}else{if(confirm("DEACTIVATE GLOBAL FIREWALL?")){await db.ref('admin/globalFirewall').set({active:false,deactivatedBy:"ADMIN",timestamp:Date.now()});globalFirewallActive=false;b.className='firewall-off';b.innerHTML='🔥 FIREWALL OFF';s.innerHTML='FIREWALL DEACTIVATED';s.style.color='#39ff14';b.classList.remove('fire-animation');alert("🔓 FIREWALL DEACTIVATED");}}}
async function checkGlobalFirewallStatus(){const s=await db.ref('admin/globalFirewall').once('value'),d=s.val();globalFirewallActive=(d&&d.active===true);const b=document.getElementById('firewallToggleBtn'),m=document.getElementById('firewallStatusMsg');if(globalFirewallActive){if(b){b.className='firewall-on';b.innerHTML='🔥 FIREWALL ON 🔥';b.classList.add('fire-animation');}if(m){m.innerHTML='FIREWALL ACTIVE';m.style.color='#ff4444';}}else{if(b){b.className='firewall-off';b.innerHTML='🔥 FIREWALL OFF';b.classList.remove('fire-animation');}if(m){m.innerHTML='FIREWALL DEACTIVATED';m.style.color='#39ff14';}}}
function banGhost(){const t=document.getElementById('banTarget').value.trim();if(!t)return;if(confirm(`Terminate ${t}?`))db.ref('banned_ghosts/'+t).set({timestamp:Date.now(),bannedBy:"ADMIN"});document.getElementById('banTarget').value='';}
function liftBan(i){if(confirm(`Recover ${i}?`))db.ref('banned_ghosts/'+i).remove();}
function purgeGhost(p){if(confirm(`Delete data for ${p}?`))db.ref('user_sessions/'+p).remove();}
async function loadStats(){const u=await db.ref('user_sessions').once('value');document.getElementById('activeUsersBadge').innerHTML=u.numChildren()+" ACTIVE";const b=await db.ref('banned_ghosts').once('value');document.getElementById('bannedBadge').innerHTML=b.numChildren()+" BANNED";}
async function getDeviceDisplayId(fp){if(!fp||fp==='---')return '---';const m=await db.ref('device_id_map/'+fp).once('value');if(m.exists())return m.val().displayId;const c=await db.ref('admin/deviceCounter').once('value');let n=(c.val()||0)+1;await db.ref('admin/deviceCounter').set(n);const id=`Dev${n}`;await db.ref('device_id_map/'+fp).set({displayId:id,createdAt:Date.now(),fingerprint:fp});return id;}
db.ref('links').on('value',s=>{const t=document.getElementById('linkData');if(!t)return;t.innerHTML='';s.forEach(c=>{const d=c.val(),cls=d.status==='available'?'status-avail':'status-used',hash=d.hash||generateHash(d.url||'');t.innerHTML+=`<tr><td>#${c.key.substr(-4)}</td><td title="${d.url||''}">${hash}</td><td><span class="status ${cls}">${d.status}</span></td><td class="ghost-id">${d.user==='NONE'?'---':d.user}</td><td><button class="icon-btn" onclick="reuseLink('${c.key}')" style="color:var(--gold);">♻️</button><button class="icon-btn" onclick="db.ref('links/${c.key}').remove()" style="color:var(--danger);">🗑️</button></td></tr>`;})});
db.ref('user_sessions').on('value',async s=>{const t=document.getElementById('ghostData');if(!t)return;t.innerHTML='';for(const c of s.val()?Object.entries(s.val()):[]){const d=c[1],last=d.lastUpdate?new Date(d.lastUpdate).toLocaleTimeString():'---',fp=d.deviceFingerprint||'---';let dev='---';if(fp!=='---')dev=await getDeviceDisplayId(fp);t.innerHTML+=`<tr><td class="ghost-id">${d.phone||'---'}</td><td style="color:var(--ghost)">₱${(d.balance||0).toLocaleString()}</td><td style="color:var(--neon);font-weight:bold;">${dev}</td><td style="font-size:9px;">${last}</td><td><button class="icon-btn" onclick="document.getElementById('banTarget').value='${d.phone}';banGhost()" style="color:var(--neon);">🔨</button><button class="icon-btn" onclick="purgeGhost('${d.phone}')" style="color:var(--danger);">💀</button></td></tr>`;}document.getElementById('activeUsersBadge').innerHTML=(s.numChildren()||0)+" ACTIVE";});
db.ref('banned_ghosts').on('value',s=>{const t=document.getElementById('banList');if(t)t.innerHTML=`<tr><td colspan="2" style="text-align:center; color:var(--danger);">⚠️ ${s.numChildren()} terminated record(s) in database</td></tr>`;document.getElementById('bannedBadge').innerHTML=s.numChildren()+" BANNED";});
db.ref('admin/globalFirewall').on('value',s=>{const d=s.val();globalFirewallActive=(d&&d.active===true);const b=document.getElementById('firewallToggleBtn'),m=document.getElementById('firewallStatusMsg');if(globalFirewallActive){if(b){b.className='firewall-on';b.innerHTML='🔥 FIREWALL ON 🔥';b.classList.add('fire-animation');}if(m){m.innerHTML='FIREWALL ACTIVE';m.style.color='#ff4444';}}else{if(b){b.className='firewall-off';b.innerHTML='🔥 FIREWALL OFF';b.classList.remove('fire-animation');}if(m){m.innerHTML='FIREWALL DEACTIVATED';m.style.color='#39ff14';}}});
if(localStorage.getItem(REMEMBER_KEY)==="true"||sessionStorage.getItem(SESSION_KEY)==="true"){sessionStorage.setItem(SESSION_KEY,"true");document.getElementById('loginOverlay').style.display='none';document.getElementById('dashboard').classList.add('active');loadStats();checkGlobalFirewallStatus();}
document.getElementById('accessKey')?.addEventListener('keypress',e=>{if(e.key==='Enter')verifyAccess();});
