/**
 * referral.js - Pure Animation Display
 * Fetches existing referral code from Firebase (generated by index.js)
 * Animates each character 1 by 1 with random rolling effect (first time only)
 * Caches code in localStorage for instant subsequent opens
 */

(function() {
    'use strict';

    // DOM elements
    const dropdownBtn = document.getElementById('dropdownBtn');
    const dropdownContent = document.getElementById('dropdownContent');
    const referralDisplay = document.getElementById('referralCodeDisplay');

    if (!dropdownBtn || !dropdownContent || !referralDisplay) {
        console.error('Missing dropdown elements');
        return;
    }

    // State
    let cachedCode = localStorage.getItem('user_referral_code');
    let animationDone = localStorage.getItem('referral_animation_done') === 'true';
    let isAnimating = false;
    let currentCode = null;

    // ========== UTILITIES ==========
    function showGoldenBar(code) {
        referralDisplay.innerHTML = `
            <div id="refGoldBar" style="background: linear-gradient(135deg, #b8860b, #d4af37, #fce883, #d4af37, #b8860b); border-radius: 16px; padding: 20px; text-align: center; box-shadow: 0 0 20px rgba(212,175,55,0.5); cursor: pointer;">
                <div style="font-size: 11px; color: #1a1100; letter-spacing: 2px;">⭐ YOUR REFERRAL CODE ⭐</div>
                <div style="font-size: 32px; font-weight: 900; color: #1a1100; letter-spacing: 6px; font-family: 'Orbitron', monospace;">${code}</div>
                <div style="font-size: 10px; color: #1a1100; margin-top: 8px;"><i class="fas fa-copy"></i> Tap to copy</div>
            </div>
        `;
        const bar = document.getElementById('refGoldBar');
        if (bar) bar.onclick = () => navigator.clipboard.writeText(code).then(() => alert('✅ Referral code copied!'));
    }

    function showLoading() {
        referralDisplay.innerHTML = `<div style="text-align:center; padding:20px;"><i class="fas fa-spinner fa-pulse"></i> Loading...</div>`;
    }

    // ========== PER-CHARACTER ANIMATION ==========
    async function animateCode(container, finalCode) {
        if (!container) return;

        const letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
        const numbers09 = '0123456789';
        const numbers06 = '0123456';
        const charSets = [letters, letters, numbers09, letters, letters, numbers06];

        container.innerHTML = '';
        const slots = [];

        // Create 6 slots
        for (let i = 0; i < 6; i++) {
            const slot = document.createElement('span');
            slot.className = 'referral-code-slot';
            slot.style.cssText = `display: inline-block; min-width: 55px; text-align: center; font-family: 'Orbitron', monospace; font-size: 32px; font-weight: 900; color: #fce883; text-shadow: 0 0 10px rgba(212,175,55,0.5); transition: all 0.1s ease;`;
            slot.textContent = '?';
            container.appendChild(slot);
            slots.push(slot);
        }

        // Animate each character sequentially
        for (let i = 0; i < 6; i++) {
            const charSet = charSets[i];
            const finalChar = finalCode[i];
            const slot = slots[i];

            // Rapid random changes (15 times)
            for (let r = 0; r < 15; r++) {
                await new Promise(resolve => setTimeout(resolve, 40));
                const randomChar = charSet.charAt(Math.floor(Math.random() * charSet.length));
                slot.textContent = randomChar;
                slot.style.transform = 'scale(1.2)';
                slot.style.opacity = '0.7';
                setTimeout(() => {
                    slot.style.transform = 'scale(1)';
                    slot.style.opacity = '1';
                }, 40);
            }

            // Settle to final character
            slot.textContent = finalChar;
            slot.style.color = '#ffffff';
            slot.style.animation = 'slotReveal 0.3s ease-out';
            await new Promise(resolve => setTimeout(resolve, 100));
        }

        // Final flash
        container.style.animation = 'pulseGold 0.5s ease';
        setTimeout(() => { if (container) container.style.animation = ''; }, 500);
    }

    // ========== FETCH CODE FROM FIREBASE (NO GENERATION) ==========
    async function fetchCodeFromFirebase() {
        const userPhone = localStorage.getItem('userPhone');
        if (!userPhone) return null;

        // Ensure Firebase is initialized
        if (typeof firebase === 'undefined' || !firebase.database) {
            if (typeof firebaseConfig !== 'undefined' && !firebase.apps.length) {
                firebase.initializeApp(firebaseConfig);
            } else {
                console.warn('Firebase not available');
                return null;
            }
        }

        try {
            const db = firebase.database();
            const snap = await db.ref('user_sessions/' + userPhone + '/referral_code').once('value');
            const code = snap.val();
            if (code && code.length === 6) {
                // Cache it
                localStorage.setItem('user_referral_code', code);
                return code;
            } else {
                console.error('No valid referral code found in Firebase for user', userPhone);
                return null;
            }
        } catch (err) {
            console.error('Firebase read error:', err);
            return null;
        }
    }

    // ========== MAIN DISPLAY LOGIC ==========
    async function displayReferralCode() {
        // If we already have a cached code and animation already done, show instantly
        if (cachedCode && animationDone) {
            showGoldenBar(cachedCode);
            return;
        }

        // If we have a cached code but animation not done yet, animate it
        if (cachedCode && !animationDone) {
            // Animate using cached code
            const animContainer = document.createElement('div');
            animContainer.style.cssText = `display: flex; justify-content: center; gap: 10px; padding: 25px 20px; background: rgba(0,0,0,0.4); border-radius: 16px;`;
            referralDisplay.innerHTML = '';
            referralDisplay.appendChild(animContainer);
            await animateCode(animContainer, cachedCode);
            showGoldenBar(cachedCode);
            localStorage.setItem('referral_animation_done', 'true');
            animationDone = true;
            return;
        }

        // No cached code, need to fetch from Firebase
        showLoading();
        const code = await fetchCodeFromFirebase();
        if (code) {
            cachedCode = code;
            // Animate
            const animContainer = document.createElement('div');
            animContainer.style.cssText = `display: flex; justify-content: center; gap: 10px; padding: 25px 20px; background: rgba(0,0,0,0.4); border-radius: 16px;`;
            referralDisplay.innerHTML = '';
            referralDisplay.appendChild(animContainer);
            await animateCode(animContainer, code);
            showGoldenBar(code);
            localStorage.setItem('referral_animation_done', 'true');
            animationDone = true;
        } else {
            // Fallback: show error
            showGoldenBar('ERROR');
            console.error('Could not retrieve referral code');
        }
    }

    // ========== DROPDOWN TOGGLE ==========
    function setupDropdown() {
        // Clone to remove existing listeners
        const newBtn = dropdownBtn.cloneNode(true);
        dropdownBtn.parentNode.replaceChild(newBtn, dropdownBtn);
        const finalBtn = newBtn;

        finalBtn.addEventListener('click', async (e) => {
            e.preventDefault();
            e.stopPropagation();
            dropdownContent.classList.toggle('show');
            const arrow = finalBtn.querySelector('.dropdown-arrow');
            if (arrow) arrow.innerHTML = dropdownContent.classList.contains('show') ? '▲' : '▼';

            if (dropdownContent.classList.contains('show')) {
                await displayReferralCode();
            }
        });

        document.addEventListener('click', (e) => {
            if (!finalBtn.contains(e.target) && !dropdownContent.contains(e.target)) {
                dropdownContent.classList.remove('show');
                const arrow = finalBtn.querySelector('.dropdown-arrow');
                if (arrow) arrow.innerHTML = '▼';
            }
        });
    }

    // ========== INIT ==========
    function init() {
        setupDropdown();
        console.log('✅ Referral animation display ready (no generation)');
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();
